### ISSUE TITLE
Jeg har funnet noe vi kanskje kan bruke

### ISSUE THREAD

**Issue by Ken9Kodehode** [chriskodehub/kodehode-course-plan#11]
Jeg fant  en Java "student registration" som bruker MySQL database som vi kanskje kunne brukt (Med litt modifikasjoner)
https://www.tutussfunny.com/jdbc-crud/

Han har lagt ved en YouTube video om åssen man bruker den & lager den.
Jeg tenker det er noe vi kanskje kunne brukt i forhold til å legge studentene inn i systemet.

Ta et titt dere og fortell hva dere tenker.

**Comment by chriskodehub** [comment]
It is best if we keep all ideas for Backend in one thread. Message moved to main thread about Backend #8
